name: Test Assessment Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Services with Docker Compose
        working-directory: ./Leistungsnachweis 
        run: |
          docker-compose up -d
          sleep 15 # Wartezeit erhöhen, um sicherzustellen, dass die Container vollständig gestartet sind

      - name: Perform Health Check
        run: |
          curl --fail http://localhost:8080/health || exit 1 # Health Check für den Assessment-Service

      - name: Get Dataset
        run: |
          curl --fail http://localhost:8080/v1/dataset -o dataset.json || exit 1

      - name: Calculate Results
        run: |
          echo '{
            "result": [
              {
                "customerId": "5bd2d637-c946-45bf-b194-d197da7da5cb",
                "consumption": 2873559000
              }
            ]
          }' > results.json

      - name: Attempt POST Request
        run: |
          curl -X POST -H "Content-Type: application/json" -d @results.json http://localhost:8080/v1/result -o post_response.txt || true

      - name: Stop and Remove Services with Docker Compose
        working-directory: ./Leistungsnachweis
        run: |
          docker-compose down
