name: Test Assessment Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Assessment Docker Image
        run: docker pull mrksdh/assessment

      - name: Run Assessment Docker Container
        run: |
          docker run -d --name assessment-test -p 8080:8080 mrksdh/assessment
          sleep 10

      - name: Run Health Check
        run: |
          curl --fail http://localhost:8080/health || exit 1

      - name: Get Dataset
        run: |
          curl --fail http://localhost:8080/v1/dataset -o dataset.json || exit 1

      - name: Calculate Results
        run: |
          echo '{
            "result": [
              {
                "customerId": "5bd2d637-c946-45bf-b194-d197da7da5cb",
                "consumption": 2873559000
              }
            ]
          }' > results.json

          curl --fail -X POST -H "Content-Type: application/json" -d @results.json http://localhost:8080/v1/result || exit 1

      - name: Stop and Remove Assessment Container
        run: |
          docker stop assessment-test
          docker rm assessment-test
