name: Test Assessment Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Pull Assessment Docker Image
        run: docker pull mrksdh/assessment

      - name: Run Assessment Docker Container
        run: |
          docker run -d --name assessment-test -p 8080:8080 mrksdh/assessment
          sleep 10

      - name: Run Health Check
        run: |
          curl --fail http://localhost:8080/health || exit 1

      - name: Compile Java Code
        run: |
          javac -cp .:gson-2.8.9.jar MyApplication.java

      - name: Execute Java Code to Send Results
        run: |
          java -cp .:gson-2.8.9.jar MyApplication
        continue-on-error: true

      - name: Check if Results were Sent
        run: |
          curl -o post_response.txt -X POST -H "Content-Type: application/json" -d @results.json http://localhost:8080/v1/result || true

          if grep -q "Not Found" post_response.txt; then
            echo "POST request sent, but the resource was not found (404)."
          else
            echo "Unexpected response: $(cat post_response.txt)"
          fi

      - name: Stop and Remove Assessment Container
        run: |
          docker stop assessment-test
          docker rm assessment-test
