name: Test Assessment Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Assessment Docker Image
        run: docker pull mrksdh/assessment

      - name: Ensure gradlew is executable
        run: chmod +x ./Leistungsnachweis/gradlew

      - name: Build Docker Image for Application
        run: |
          docker build -t leistungsnachweis ./Leistungsnachweis

      - name: Start Services with Docker Compose
        run: |
          docker-compose up -d
          sleep 10 # Wait for containers to start

      - name: Perform Health Check
        run: |
          curl --fail http://localhost:8080/health || exit 1

      - name: Get Dataset
        run: |
          curl --fail http://localhost:8080/v1/dataset -o dataset.json || exit 1

      - name: Calculate Results
        run: |
          echo '{
            "result": [
              {
                "customerId": "5bd2d637-c946-45bf-b194-d197da7da5cb",
                "consumption": 2873559000
              }
            ]
          }' > results.json

      - name: Attempt POST Request
        run: |
          curl -X POST -H "Content-Type: application/json" -d @results.json http://localhost:8080/v1/result -o post_response.txt || true

      - name: Stop and Remove Services with Docker Compose
        run: |
          docker-compose down

      - name: Run Gradle Tests
        working-directory: Leistungsnachweis
        run: |
          chmod +x gradlew  # Ensure gradlew is executable
          ./gradlew test
